In [10]:
import numpy as np
import pandas as pd

In [22]:
df =pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [23]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

**Back Propogation from scratch**

In [13]:
def initialise_parameters(layer_dims): 
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)
    
    for l in range(1,L):
        parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
        
    return parameters  
        

In [14]:
initialise_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [15]:
def linear_forward(A_prev,W,b):
    Z= np.dot(W.T,A_prev)+b
    return Z

In [54]:
#Forward Propogation
def L_layer_forward(X,parameters):
    A = X
    L = len(parameters) //2
    for l in range(1,L+1):
        A_prev = A
        Wl = parameters['W' + str(l)]
        bl = parameters['b' + str(l)]
        #print("A"+str(l-1)+":",A_prev)
        #print("w"+str(l)+":",Wl)
        #print("b"+str(l)+":",bl)
        #print("--"*20)
        
        A = linear_forward(A_prev,Wl,bl)
        #print("A"+str(l)+":",A)
        #print("**"*20)
    return A,A_prev

In [29]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1) # shape(no. of feature,no. of training eg)
y = df[['lpa']].values[0][0]

parameters = initialise_parameters([2,2,1])

In [30]:
y_hat,A1 = L_layer_forward(X,parameters)

A0: [[8]
 [8]]
w1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
w2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************


In [31]:
#Loss Function:
(y-0.32)**2

13.5424

In [33]:
y_hat = y_hat[0][0]

In [34]:
A1

array([[1.6],
       [1.6]])

In [36]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] +(0.001 * 2 * (y-y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] +(0.001 * 2 * (y-y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['b2'][0][0] +(0.001 * 2 * (y-y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] +(0.001 * 2 * (y-y_hat)*parameters['W2'][0][0] * X[0][0])
    parameters['W1'][1][0] = parameters['W1'][1][0] +(0.001 * 2 * (y-y_hat)*parameters['W2'][0][0] * X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] +(0.001 * 2 * (y-y_hat)*parameters['W2'][0][0])
    
    parameters['W1'][1][0] = parameters['W1'][1][0] +(0.001 * 2 * (y-y_hat)*parameters['W2'][1][0] * X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] +(0.001 * 2 * (y-y_hat)*parameters['W2'][1][0] * X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] +(0.001 * 2 * (y-y_hat)*parameters['W2'][1][0])

In [37]:
update_parameters(parameters,y,y_hat,A1,X)

In [38]:
parameters

{'W1': array([[0.10658137, 0.1       ],
        [0.11316274, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.00736]])}

In [39]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1) # shape(no. of feature,no. of training eg)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)

A0: [[7]
 [9]]
w1: [[0.10658137 0.1       ]
 [0.11316274 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.76535694]
 [1.66005501]]
****************************************
A1: [[1.76535694]
 [1.66005501]]
w2: [[0.111776]
 [0.111776]]
b2: [[0.00736]]
----------------------------------------
A2: [[0.39023885]]
****************************************


In [40]:
update_parameters(parameters,y,y_hat,A1,X)

In [41]:
parameters


{'W1': array([[0.1148454, 0.1      ],
        [0.1319893, 0.117126 ]]),
 'b1': array([[0.00200325],
        [0.0019943 ]]),
 'W2': array([[0.12805175],
        [0.12708091]]),
 'b2': array([[0.01657952]])}

In [42]:
X = df[['cgpa','profile_score']].values[2].reshape(2,1) # shape(no. of feature,no. of training eg)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)

A0: [[ 6]
 [10]]
w1: [[0.1148454 0.1      ]
 [0.1319893 0.117126 ]]
b1: [[0.00200325]
 [0.0019943 ]]
----------------------------------------
A1: [[2.01096869]
 [1.77325428]]
****************************************
A1: [[2.01096869]
 [1.77325428]]
w2: [[0.12805175]
 [0.12708091]]
b2: [[0.01657952]]
----------------------------------------
A2: [[0.49943435]]
****************************************


In [43]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.12475795, 0.1       ],
        [0.15818607, 0.13325242]]),
 'b1': array([[0.00365534],
        [0.00360694]]),
 'W2': array([[0.15017468],
        [0.14658872]]),
 'b2': array([[0.02758065]])}

In [46]:
X = df[['cgpa','profile_score']].values[3].reshape(2,1) # shape(no. of feature,no. of training eg)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)

A0: [[ 5]
 [12]]
w1: [[0.13619157 0.1       ]
 [0.1965008  0.15935012]]
b1: [[0.00594206]
 [0.00578175]]
----------------------------------------
A1: [[3.04490949]
 [2.41798317]]
****************************************
A1: [[3.04490949]
 [2.41798317]]
w2: [[0.18192196]
 [0.17301845]]
b2: [[0.04015046]]
----------------------------------------
A2: [[1.01244207]]
****************************************


In [47]:
update_parameters(parameters,y,y_hat,A1,X)
parameters

{'W1': array([[0.14926751, 0.1       ],
        [0.23997636, 0.18837407]]),
 'b1': array([[0.00855725],
        [0.00820041]]),
 'W2': array([[0.21838511],
        [0.20197408]]),
 'b2': array([[0.05212558]])}

In [56]:
parameters = initialise_parameters([2,2,1])
epochs = 5
for i in range(epochs):
    Loss = []
    
    for j in range(df.shape[0]):
        
        X= df[['cgpa','profile_score']].values[j].reshape(2,1)
        y = df[['lpa']].values[j][0]
        
        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]
        
        update_parameters(parameters,y,y_hat,A1,X)
        Loss.append((y-y_hat)**2)
    print('Epoch: ',i+1,'Loss: ',np.array(Loss).mean())
    
parameters

Epoch:  1 Loss:  26.13713395667704
Epoch:  2 Loss:  18.582961698517934
Epoch:  3 Loss:  8.550163628250722
Epoch:  4 Loss:  2.2116441879338877
Epoch:  5 Loss:  0.6943526394000419


{'W1': array([[0.27982712, 0.1       ],
        [0.56353813, 0.36418959]]),
 'b1': array([[0.0297719 ],
        [0.02565513]]),
 'W2': array([[0.51465406],
        [0.39198752]]),
 'b2': array([[0.11170335]])}

In [2]:
!pip install tensorflow

**Library implementation**

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2,activation = 'linear',input_dim=2))
model.add(Dense(1,activation = 'linear'))

In [7]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
model.get_weights()

[array([[ 0.2845956 ,  0.6163877 ],
        [-1.2073872 , -0.11946058]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.7627646],
        [-0.1021657]], dtype=float32),
 array([0.], dtype=float32)]

In [17]:
new_weights = [np.array([[0.1,0.1],
                        [0.1,0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([[0.1],
                       [0.1]],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [18]:
model.set_weights(new_weights)

In [19]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [20]:
optimizer = keras.optimizers.Adam(learning_rate =0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [24]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 27.4597
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 31.4708 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 31.1207 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 30.2219 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 21.5167 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 30.0088  
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 25.4250 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 20.5357 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 30.0906 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24.3329 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.1609 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22.7530 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3549 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 23.2453 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 18.6628  
Epoch 16/75
4/4 ━━

In [25]:
model.get_weights()

[array([[0.37353286, 0.37353286],
        [0.3654555 , 0.3654555 ]], dtype=float32),
 array([0.27221525, 0.27221525], dtype=float32),
 array([[0.37280497],
        [0.37280497]], dtype=float32),
 array([0.20464602], dtype=float32)]